-- Smart Home Bakery Management Platform - Database Schema
-- PostgreSQL Database for storing recipes, ingredients, orders, and analytics

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(20),
    location VARCHAR(120),
    bakery_name VARCHAR(120),
    business_status VARCHAR(50) DEFAULT 'hobby', -- 'hobby' or 'professional'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Recipes Table
CREATE TABLE IF NOT EXISTS recipes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    cake_type VARCHAR(120) NOT NULL,
    weight VARCHAR(20) NOT NULL, -- '500g', '1kg', '2kg', '3kg'
    servings INTEGER,
    is_eggless BOOLEAN DEFAULT FALSE,
    baking_temp INTEGER, -- in Celsius
    baking_time INTEGER, -- in minutes
    tin_size VARCHAR(50),
    description TEXT,
    difficulty_level VARCHAR(50) DEFAULT 'medium', -- 'easy', 'medium', 'hard'
    ai_generated BOOLEAN DEFAULT TRUE,
    image_url VARCHAR(255),
    rating FLOAT DEFAULT 0,
    times_made INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Recipe Instructions Table
CREATE TABLE IF NOT EXISTS recipe_instructions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER NOT NULL,
    step_number INTEGER NOT NULL,
    instruction TEXT NOT NULL,
    duration_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
);

-- Ingredients Table
CREATE TABLE IF NOT EXISTS ingredients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    unit VARCHAR(50) NOT NULL, -- 'grams', 'ml', 'teaspoon', 'tablespoon', 'cups', 'litre'
    category VARCHAR(50) NOT NULL, -- 'flour', 'sugar', 'butter', 'eggs', 'milk', 'chocolate', 'spices', etc.
    price_per_unit FLOAT NOT NULL,
    total_quantity FLOAT NOT NULL, -- total quantity purchased
    stock_quantity FLOAT NOT NULL, -- current stock
    min_stock_alert FLOAT,
    last_purchased_date DATE,
    supplier VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Recipe Ingredients Mapping
CREATE TABLE IF NOT EXISTS recipe_ingredients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity FLOAT NOT NULL,
    unit VARCHAR(50) NOT NULL,
    is_optional BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    customer_phone VARCHAR(20),
    customer_email VARCHAR(120),
    cake_type VARCHAR(120) NOT NULL,
    cake_weight VARCHAR(20),
    flavor VARCHAR(120),
    theme VARCHAR(120),
    budget FLOAT,
    special_requirements TEXT,
    order_date DATE NOT NULL,
    delivery_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'accepted', 'in_progress', 'completed', 'cancelled'
    estimated_ingredient_cost FLOAT,
    decoration_difficulty VARCHAR(50),
    time_required_hours FLOAT,
    estimated_profit FLOAT,
    actual_cost FLOAT,
    selling_price FLOAT,
    actual_profit FLOAT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Order Items (detailed breakdown)
CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_used FLOAT NOT NULL,
    unit VARCHAR(50) NOT NULL,
    cost FLOAT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    category VARCHAR(50) NOT NULL, -- 'ingredients', 'equipment', 'packaging', 'utilities', 'marketing', 'other'
    amount FLOAT NOT NULL,
    description TEXT,
    expense_date DATE NOT NULL,
    payment_method VARCHAR(50), -- 'cash', 'card', 'online', 'check'
    receipt_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Profit Reports Table
CREATE TABLE IF NOT EXISTS profit_reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    report_date DATE NOT NULL,
    total_orders INTEGER,
    total_revenue FLOAT,
    total_ingredients_cost FLOAT,
    total_expenses FLOAT,
    total_profit FLOAT,
    average_profit_per_cake FLOAT,
    most_profitable_flavor VARCHAR(120),
    most_selling_flavor VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Bakery Market Rates Table
CREATE TABLE IF NOT EXISTS bakery_market_rates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    location VARCHAR(120) NOT NULL,
    bakery_name VARCHAR(120),
    bakery_url TEXT,
    cake_type VARCHAR(120) NOT NULL,
    weight VARCHAR(20),
    price FLOAT NOT NULL,
    currency VARCHAR(10) DEFAULT 'INR',
    last_updated DATE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Decoration References Table
CREATE TABLE IF NOT EXISTS decoration_references (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    cake_weight VARCHAR(20),
    style VARCHAR(120) NOT NULL,
    image_url TEXT,
    source VARCHAR(50), -- 'pinterest', 'instagram', 'custom'
    cream_quantity_grams INTEGER,
    piping_style VARCHAR(120),
    drip_design VARCHAR(120),
    flower_quantity INTEGER,
    fondant_usage TEXT,
    difficulty_level VARCHAR(50),
    estimated_time_hours FLOAT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- AI Image Generations Table
CREATE TABLE IF NOT EXISTS ai_generated_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    prompt TEXT NOT NULL,
    image_url TEXT,
    ai_provider VARCHAR(50) NOT NULL, -- 'openai', 'gemini'
    model_used VARCHAR(100),
    usage_tokens INTEGER,
    cost FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Inventory Alerts Table
CREATE TABLE IF NOT EXISTS inventory_alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    alert_type VARCHAR(50) NOT NULL, -- 'low_stock', 'out_of_stock', 'expiring_soon'
    message TEXT,
    is_resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

-- Baking Mistakes & Solutions Table
CREATE TABLE IF NOT EXISTS baking_mistakes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem TEXT NOT NULL,
    symptoms TEXT NOT NULL,
    solutions TEXT NOT NULL, -- JSON format with multiple solutions
    prevention_tips TEXT,
    affected_cake_types TEXT, -- JSON array

    is_verified BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- User Preferences Table
CREATE TABLE IF NOT EXISTS user_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    theme VARCHAR(20) DEFAULT 'light', -- 'light', 'dark'
    language VARCHAR(10) DEFAULT 'en',
    currency VARCHAR(10) DEFAULT 'INR',
    notification_email BOOLEAN DEFAULT TRUE,
    notification_sms BOOLEAN DEFAULT FALSE,
    auto_low_stock_alert BOOLEAN DEFAULT TRUE,
    weekly_profit_report BOOLEAN DEFAULT TRUE,
    preferred_ai_provider VARCHAR(50) DEFAULT 'openai', -- 'openai', 'gemini'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Feedback & Ratings Table
CREATE TABLE IF NOT EXISTS feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    recipe_id INTEGER,
    order_id INTEGER,
    rating INTEGER, -- 1-5
    comment TEXT,
    category VARCHAR(50), -- 'recipe_accuracy', 'cost_calculation', 'ai_recommendation', 'ui_ux', 'other'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- Create Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_recipes_user_id ON recipes(user_id);
CREATE INDEX IF NOT EXISTS idx_recipes_cake_type ON recipes(cake_type);
CREATE INDEX IF NOT EXISTS idx_ingredients_user_id ON ingredients(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(order_date);
CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_profit_reports_user_id ON profit_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_profit_reports_date ON profit_reports(report_date);
CREATE INDEX IF NOT EXISTS idx_bakery_rates_location ON bakery_market_rates(location);
CREATE INDEX IF NOT EXISTS idx_bakery_rates_cake_type ON bakery_market_rates(cake_type);

